#!/bin/sh
dest=`realpath $0`
dest=${dest%/*}

cd
tmp=`mktemp -d env-XXXX.bak`
echo saving old env files to `pwd`/$tmp.tgz

for t in `ls -A $dest/home-env`; do
    mv $t $tmp 2>/dev/null
    ln -sf $dest/home-env/$t $t
done

echo copying .config/urations
mkdir -p ~/.config
ln -sf $dest/nvim ~/.config/nvim

echo compiling goodies
cd env
go build statusbar.go
