#!/bin/sh

# Włącz/wyłącz ściąganie torrentów
# TODO włączaj cebulę automatycznie przy wykryciu sieci z oneplusa

dir=$(dirname `readlink $0`)
# zakłada włączoną wtyczkę Scheduler
path=~/.config/deluge/scheduler.conf

if [ ${1:-on} = on ]; then
    cp $dir/cebula.conf $path
    echo Deluge aktywny w godzinach 1-8
elif [ $1 = off ]; then
    cp $dir/yolo.conf $path
    echo Deluge aktywny całą dobę
fi

# deluge nie zaklada ze ktos moze mu zmienic konfig
pkill -f deluge
